### Read all users
GET http://localhost:5000/products 
// GET dosen't have any body

### Read a user by id
GET http://localhost:5000/products/suzuki

### Create  new user
POST http://localhost:5000/products
Content-Type: application/json 

{
    "productId" : 1,
    "name" : "car",
    "brand" : "suzuki", 
    "price" : 1435
}

### Update a user
PUT http://localhost:5000/products
Content-Type: application/json

{
    "productId" : 1,
    "name" : "jeep",
    "brand" : "Thar", 
    "price" : 1445
}

### Delete a user by ID
DELETE http://localhost:5000/products/1

// DELETE dosen't have any body. We mention ID of the data in the path itself