### Read all users
GET http://localhost:1500/user-api/users 

### Read all products
GET http://localhost:1500/product-api/products 

### Read a user by id
GET http://localhost:1500/user-api/users/1

### Read a products by brand
GET http://localhost:1500/product-api/products/suzuki

### Create  new user
POST http://localhost:1500/user-api/users
Content-Type: application/json 

{ 
    "id" : 1,
    "name" : "Samanvi",
    "age" : 18
}

### Create  new product
POST http://localhost:1500/product-api/products
Content-Type: application/json 

{
    "productId" : 1,
    "name" : "car",
    "brand" : "suzuki", 
    "price" : 1435
}

### Update a user
PUT http://localhost:1500/user-api/users
Content-Type: application/json

{ 
    "id" : 1, 
    "name" : "Sanjana",
    "age" : 20
}

### Update a product
PUT http://localhost:1500/product-api/products
Content-Type: application/json

{
    "productId" : 1,
    "name" : "jeep",
    "brand" : "Mahendra", 
    "price" : 1445
}

### Delete a user by ID
DELETE http://localhost:1500/user-api/users/1

### Delete a product by ID
DELETE http://localhost:1500/product-api/products/1