### Read all orders
GET http://localhost:3000/orders

### Read an order by id
GET http://localhost:3000/orders/1

### Create a new order
POST http://localhost:3000/orders
Content-Type: application/json

{
    "id" : 1,
    "product" : "Laptop",
    "price" : 354666
}

### Update an order
PUT http://localhost:3000/orders
Content-Type: application/json

{
    "id" : 1,
    "product" : "PC",
    "price" : 876654
}

### DELETE an order by id
DELETE http://localhost:3000/orders/1
